FROM mongo:latest

RUN apt-get update
RUN apt-get install -y netcat

COPY /wait-for-mongo.sh /

RUN touch entrypoint.sh
RUN echo "echo \"hello from entrypoint.sh\"" >> entrypoint.sh
RUN echo "/wait-for-mongo.sh & /usr/bin/mongod" >> entrypoint.sh
RUN chmod +x entrypoint.sh

ENTRYPOINT ./entrypoint.sh