FROM mongo:latest

RUN apt-get update
RUN apt-get install -y netcat

COPY /wait-for-mongo.sh /
COPY /entrypoint.sh /
COPY /books.json /
RUN echo "mongoimport -d myDatabase -c books --file books.json" | tee -a wait-for-mongo.sh

ENTRYPOINT ./entrypoint.sh